stages:
    load_data:
       cmd: python src/stage_01_load_save.py  --config=config/config.yaml
       deps:
        - src/stage_01_load_save.py
        - src/utils/all_utils.py
        - config/config.yaml
       outs:
        - data/Flicker8k_Dataset
        - data/Flickr8k_text
        - data/Pickle  
        - data/glove
    prepaired_data:
       cmd: python src/stage_02_data_preparation.py  --config=config/config.yaml   
       deps:
        - src/stage_02_data_preparation.py
        - src/utils/all_utils.py
        - src/utils/text_img_data_preparation.py
        - config/config.yaml
        
       outs:
        - prepaired_data/vocab_size_dir
        - prepaired_data/max_length_dir
        - prepaired_data/wordtoix_dir     
        - prepaired_data/train_img
        - prepaired_data/test_img
        - prepaired_data/train_descriptions_dir
        - prepaired_data/ixtoword_dir 