artifacts:
   ARTIFACTS_DIR: artifacts
   TRAINED_MODEL_DIR: model
   BASE_MODEL_DIR: base_model
   BASE_MODEL_NAME: inception_base_model.h5
   UPDATED_BASE_MODEL_NAME: updated_inception_base_model.h5
   CHECKPOINT_DIR:  checkpoints
   BASE_LOG_DIR: Base_model_dir
   TENSORBOARD_ROOT_LOG_DIR: Tensorboard_log_dir
   CALLBACKS_DIR: callbacks
   DATA_DIR: data
   IMAGE_DATA: Flicker8k_Dataset
   TEXT_DATA: Flickr8k_text
   TOKEN_PATH_NAME: Flickr8k.token.txt
   TRAIN_PATH: Flickr_8k.trainImages.txt
   TEST_PATH: Flickr_8k.testImages.txt
   GLOVE_DIR: glove 
   GLOVE_FILE: glove.6B.200d.txt
   PICKLE: Pickle
   TRAIN_FEATURES_FILE_NAME: encoded_train_images.pkl 
   TEST_FEATURES_FILE_NAME: encoded_test_images.pkl 

source_download_path:
   - ../data/Flicker8k_Dataset
   - ../data/Flickr8k_text
   - ../data/Pickle
   - ../data/glove

local_data_dirs:
   - data/Flicker8k_Dataset
   - data/Flickr8k_text
   - data/Pickle  
   - data/glove

prepaired_data_dir:
   - prepaired_data/vocab_size_dir
   - prepaired_data/max_length_dir
   - prepaired_data/wordtoix_dir     
   - prepaired_data/train_img
   - prepaired_data/test_img
   - prepaired_data/train_descriptions_dir