artifacts:
   ARTIFACTS_DIR: artifacts
   TRINED_MODEL_DIR: model
   BASE_MODEL_DIR: base_model
   BASE_MODEL_NAME: inception_base_model.h5
   UPDATED_BASE_MODEL_NAME: updated_inception_base_model.h5
   CHECKPOINT_DIR:  checkpoints
   BASE_LOG_DIR: Base_model_dir
   TENSORBOARD_ROOT_LOG_DIR: Tensorboard_log_dir
   CALLBACKS_DIR: callbacks

source_download_path:
   - ../data/Flicker8k_Dataset
   - ../data/Flickr8k_text
   - ../data/Pickle

local_data_dirs:
   - data/Flicker8k_Dataset
   - data/Flickr8k_text
   - data/Pickle  